import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import hre from "hardhat";

const sharedSrc = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../packages/shared/src",
);

const artifact = await hre.artifacts.readArtifact("LostAndFound");

const abiSource = `// Generated by contracts/scripts/export-abi.ts. Do not edit by hand.
// Run \`pnpm --filter contracts export-abi\` after changing LostAndFound.sol.

export const lostAndFoundAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

await mkdir(sharedSrc, { recursive: true });
await writeFile(path.join(sharedSrc, "abi.ts"), abiSource);

console.log(
  `Wrote ${artifact.abi.length} ABI entries to packages/shared/src/abi.ts`,
);
