import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import hre from "hardhat";

import {
  contractsDir,
  KNOWN_DEPLOYMENTS,
  LOCALHOST_DEPLOYMENT,
  readDeployment,
  type Deployment,
} from "./lib/deployments.ts";

const sharedSrc = path.resolve(contractsDir, "../packages/shared/src");

const artifact = await hre.artifacts.readArtifact("LostAndFound");

const abiSource = `// Generated by contracts/scripts/export-abi.ts. Do not edit by hand.
// Run \`pnpm --filter contracts export-abi\` after changing LostAndFound.sol.

export const lostAndFoundAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

const deployments: { name: string; deployment: Deployment }[] = [
  { name: "localhost", deployment: LOCALHOST_DEPLOYMENT },
];
for (const { name, deploymentId } of KNOWN_DEPLOYMENTS) {
  const deployment = await readDeployment(deploymentId);
  if (deployment !== undefined) deployments.push({ name, deployment });
}

const entries: string[] = [];
const byChain: string[] = [];
for (const { name, deployment } of deployments) {
  entries.push(`  ${name}: {
    deploymentId: "${deployment.deploymentId}",
    chainId: ${deployment.chainId},
    address: "${deployment.address}",
    deployTx: "${deployment.deployTx}",
    deployBlock: ${deployment.deployBlock}n,
  },`);
  // Staging is a second contract on Sepolia; the per-chain map holds the main one.
  if (name !== "sepoliaStaging") {
    byChain.push(`  ${deployment.chainId}: lostAndFoundDeployments.${name},`);
  }
}

const addressesSource = `// Generated by contracts/scripts/export-abi.ts from contracts/ignition/deployments
// (localhost is the fixed first-deploy address on a fresh node).
// Do not edit by hand. Run \`pnpm --filter contracts export-abi\` after a deployment.

export interface LostAndFoundDeployment {
  /** Ignition deployment id (\`--deployment-id\`). */
  deploymentId: string;
  chainId: number;
  address: \`0x\${string}\`;
  /** Hash of the contract creation transaction. */
  deployTx: \`0x\${string}\`;
  /** Block of the creation transaction; start event queries and the subgraph here. */
  deployBlock: bigint;
}

export const lostAndFoundDeployments = {
${entries.join("\n")}
} as const satisfies Record<string, LostAndFoundDeployment>;

/** Main LostAndFound deployment per chain ID. */
export const lostAndFoundAddresses: Partial<
  Record<number, LostAndFoundDeployment>
> = {
${byChain.join("\n")}
};
`;

await mkdir(sharedSrc, { recursive: true });
await writeFile(path.join(sharedSrc, "abi.ts"), abiSource);
await writeFile(path.join(sharedSrc, "addresses.ts"), addressesSource);

console.log(
  `Wrote ${artifact.abi.length} ABI entries to packages/shared/src/abi.ts`,
);
console.log(
  `Wrote ${entries.length} deployment(s) to packages/shared/src/addresses.ts`,
);
