import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Turns `hardhat test --gas-stats-json cache/gas-stats.json` output into docs/report/gas.md.

interface Stat {
  min: number;
  max: number;
  avg: number;
  median: number;
  count: number;
}

interface GasStats {
  contracts: Record<
    string,
    {
      contractName: string;
      deployment?: Stat & { runtimeSize: number };
      functions: Record<string, Stat>;
    }
  >;
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const stats = JSON.parse(
  await readFile(path.join(root, "cache/gas-stats.json"), "utf8"),
) as GasStats;

const contract = stats.contracts["contracts/LostAndFound.sol:LostAndFound"];
if (!contract) throw new Error("No gas stats for LostAndFound");

const row = (name: string, s: Stat) =>
  `| \`${name}\` | ${s.min} | ${s.avg} | ${s.median} | ${s.max} | ${s.count} |`;

const lines = [
  "# Gas report",
  "",
  "Generated by `pnpm --filter contracts gas` from the TypeScript test suite (Hardhat 3 `--gas-stats`,",
  "solc 0.8.34, optimizer on, 200 runs). Only successful calls are measured. View functions show the",
  "cost of calling them in a transaction; reading them off-chain is free.",
  "",
  "## LostAndFound functions",
  "",
  "| Function | Min | Average | Median | Max | Calls |",
  "| --- | --- | --- | --- | --- | --- |",
  ...Object.entries(contract.functions)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, s]) => row(name, s)),
  "",
];

if (contract.deployment) {
  const d = contract.deployment;
  lines.push(
    "## Deployment",
    "",
    "| Min | Average | Median | Max | Deployments | Runtime bytecode (bytes) |",
    "| --- | --- | --- | --- | --- | --- |",
    `| ${d.min} | ${d.avg} | ${d.median} | ${d.max} | ${d.count} | ${d.runtimeSize} |`,
    "",
  );
}

const out = path.resolve(root, "../docs/report/gas.md");
await writeFile(out, lines.join("\n"));
console.log(`Wrote ${path.relative(path.resolve(root, ".."), out)}`);
