// Generated by contracts/scripts/export-abi.ts from contracts/ignition/deployments.
// Do not edit by hand. Run `pnpm --filter contracts export-abi` after a deployment.

export interface LostAndFoundDeployment {
  /** Ignition deployment id (`--deployment-id`). */
  deploymentId: string;
  chainId: number;
  address: `0x${string}`;
  /** Hash of the contract creation transaction. */
  deployTx: `0x${string}`;
  /** Block of the creation transaction; start event queries and the subgraph here. */
  deployBlock: bigint;
}

export const lostAndFoundDeployments = {
  localhost: {
    deploymentId: "chain-31337",
    chainId: 31337,
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    deployTx: "0xbe8e7a9e9ae396d19fa3a725a15d1146f8941dec57928457762b5526f8e46c8b",
    deployBlock: 1n,
  },
} as const satisfies Record<string, LostAndFoundDeployment>;

/** Main LostAndFound deployment per chain ID. */
export const lostAndFoundAddresses: Partial<
  Record<number, LostAndFoundDeployment>
> = {
  31337: lostAndFoundDeployments.localhost,
};
